### PR TITLE
Feature/hmpope 23 apply online

### PR DESCRIPTION
**Pull request by bendiggle**
- Added apply online step for track-application.
- Added `/track-application` baseUrl.
- Added acceptance tests for the apply online step
- Added back button translation to buttons common directory
- Moved journey translation from enquiries to common so all apps have access to the header translation

### CODE REVIEW

**Comment by easternbloc** [comment]
FailyMcFailedBuild

**Comment by bendiggle** [comment]
@easternbloc @joefitter @gxxm 👀

**Comment by easternbloc** [comment]
HM POPE?

**Comment by joefitter** [comment]
WORST JIRA TICKET PREFIX EVER

**Comment by bendiggle** [comment]
But best PR ever?? MERGE!

**Pull request merged**
