### PR TITLE
Feature/hmpope 22 what enquiry

### PR DESCRIPTION
**Pull request by bendiggle**
- Created structure for the different apps in the form. Each app is used based on the option selected on the first page. I have done this to split up the form to make it easier to understand and navigate.
- Create What type of enquiry page with 6 options with each one going to a different journey.
- Added acceptance tests for each option ensuring they go to the correct page.
- Added common directory as a temp measure for button translations until it has been done to bootstrap.
- Fixed issue with the acceptance tests json file where the name of the steps file was different to the actual file itself

### CODE REVIEW

**Comment by joefitter** [comment]
LGTM!

**Comment by joefitter** [comment]
There's a problem with dotfiles currently - we may need to just commit dotfiles to this repo to get build working

**Comment by joefitter** [comment]
but w/e ignore failing build for now

**Comment by joefitter** [comment]
@gxxm @easternbloc

**Comment by bendiggle** [comment]
@joefitter Yeah, I can do another PR after this with the relevant dotfiles. Btw, have you got the travis yml file working for complaints?

**Comment by joefitter** [comment]
yeah - this works - https://github.com/UKHomeOffice/UKVI-Complaints/pull/4/files#diff-354f30a63fb0907d4ad57269548329e3R1 you need to install phantomjs as a dev dep though

**Comment by gxxm** [comment]
:thumbsup: :thumbsup:

**Pull request merged**
