### PR TITLE
Feature/hmpope 24 track online

### PR DESCRIPTION
**Pull request by bendiggle**
- Added track-online step
- Added translations for the step
- Added template for step
- Removed README file as now template has been added
- Changed acceptance test to look for text on the page instead of the url

### CODE REVIEW

**Comment by joefitter** [comment]
I didn't mention this on your previous PR, but I should have done... can we please extract all strings to a constants or settings.js file? thanksyouverymuchplease x

**Comment by bendiggle** [comment]
@joefitter Do you mean for the acceptance tests?

**Comment by joefitter** [comment]
JA

**Comment by joefitter** [comment]
How about this for a crazy idea... we import and use the translations JSON files in the acceptance tests... I know.. MENTAL right?

**Comment by bendiggle** [comment]
@joefitter Good idea! I'll do the ones relevant to this step in this pr. And then the others in another. Is that ok?

**Comment by bendiggle** [comment]
hmmmmm actually, maybe they should all be done together

**Comment by joefitter** [comment]
up to you I guess, If you want to do them all together I guess it makes sense to merge this PR first

**Comment by joefitter** [comment]
so that being said LGTM @gxxm @easternbloc

**Comment by gxxm** [comment]
:thumbsup: :thumbsup:

**Pull request merged**
